### PR TITLE
Feat/admin invoice update

### PR DESCRIPTION
**Pull request by cballrun**
## Pull request type
Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please describe):
## Problem/feature
_What problem are you trying to solve?_
Creation of admin invoice update feature
## Solution
_How did you solve the problem?_
New route for admin invoice
Form in admin invoice show invoice info section
update method in Admin Invoices controller
Spec file
## Checklist
- [x] Code compiles correctly
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] All tests passing
- [ ] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by mullinsand** [comment]
I slimmed down the logic in the update method on the controller for admin invoices. Everything looks good and I like the borrowing from other sections where the code has already been tested and works. Tested it out aggressively on the server.

**Comment by mullinsand** [comment]
`And I see that the invoice's current status is selected` was the only bit of requirement that wasn't included in your feature so I just added it to the form but didn't add a test. I figured you could check it out and add a test for it. This is in the admin/invoices/show page

**Review by mullinsand — CHANGES_REQUESTED** [review]
Please add a test for the feature described in the comments. Beside that it all looks pretty good! Thanks for doing this!

**Comment by cballrun** [comment]
Requested test has been added!

**Review by mullinsand — APPROVED** [review]
Thanks for adding that test! Nice job!

**Pull request merged**
